# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iCt9V0WI-BxxYbiUhcOZjfzny5gc9BN5
"""

from urllib.request import urlopen
from bs4 import BeautifulSoup
import re

html=urlopen("https://en.wikipedia.org/wiki/CNN")
bs=BeautifulSoup(html,"html.parser")
for link in bs.find('div', {'id':'bodyContent'}).find_all(
    'a', href=re.compile('^(/wiki/)((?!:).)*$')):
    if 'href' in link.attrs:
      print(link.attrs['href'])

